workflows:
  n-gen-voice-studio-android:
    name: N-Gen Voice Studio Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd your_flutter_project_folder
          flutter pub get
      - name: Build Release APK
        script: |
          cd your_flutter_project_folder
          flutter build apk --release
    artifacts:
      - your_flutter_project_folder/build/app/outputs/flutter-apk/app-release.apk
